# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocategory',
            name='image',
        ),
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='videos.VideoCategory', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default=1, upload_to='author', verbose_name='\u0424\u043e\u0442\u043e'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profession',
            field=models.CharField(default='112', max_length=80, verbose_name='\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Author', verbose_name='\u0410\u0432\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video', verbose_name='\u0412\u0438\u0434\u0435\u043e'),
        ),
    ]
