# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_status'),
        ('videos', '0004_auto_20161201_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Status', verbose_name='status'),
            preserve_default=False,
        ),
    ]
