# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20161210_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='videos.Author', verbose_name='\u041f\u043e\u043b\u044c\u0437\u044c\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('video', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u043d\u043d\u043e\u0435 \u0432\u0438\u0434\u0435\u043e')),
            ],
            options={
                'db_table': 'video_history',
                'verbose_name': '\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u0432\u0438\u0434\u0435\u043e',
                'verbose_name_plural': '\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b \u0432\u0438\u0434\u0435\u043e',
            },
        ),
    ]
