# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=80, null=True)),
                ('keywords', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('video_url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=b'')),
                ('title', models.CharField(max_length=80, null=True)),
                ('keywords', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.VideoCategory', verbose_name='parent category')),
            ],
            options={
                'db_table': 'video_cats',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.VideoCategory'),
        ),
    ]
