# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pic',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='pic',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
