# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161004_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='pic',
        ),
    ]
