# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161004_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='relative_uri',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='relative_uri',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.VideoCategory', verbose_name='parent category'),
        ),
    ]
