# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161004_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='relative_uri',
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='relative_uri',
        ),
    ]
