# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161019_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='author',
        ),
    ]
