# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161020_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profession',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='audiostream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='videostreamset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
