# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161109_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiostream',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a\u043e-\u043f\u043e\u043d\u044f\u0442\u043d\u044b\u0439 URL'),
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a\u043e-\u043f\u043e\u043d\u044f\u0442\u043d\u044b\u0439 URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a\u043e-\u043f\u043e\u043d\u044f\u0442\u043d\u044b\u0439 URL'),
        ),
        migrations.AddField(
            model_name='videocategory',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a\u043e-\u043f\u043e\u043d\u044f\u0442\u043d\u044b\u0439 URL'),
        ),
        migrations.AddField(
            model_name='videostream',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a\u043e-\u043f\u043e\u043d\u044f\u0442\u043d\u044b\u0439 URL'),
        ),
        migrations.AddField(
            model_name='videostreamset',
            name='url',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a\u043e-\u043f\u043e\u043d\u044f\u0442\u043d\u044b\u0439 URL'),
        ),
    ]
