# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161113_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('keywords', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('url', models.CharField(blank=True, max_length=80, null=True, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a\u043e-\u043f\u043e\u043d\u044f\u0442\u043d\u044b\u0439 URL')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.AlterField(
            model_name='audiostream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audio_stream_pic', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='videostream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='video_stream_pic', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
