# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20161116_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videostreamset',
            options={'verbose_name': 'Stream channel', 'verbose_name_plural': 'Stream channels'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='videostream',
            old_name='image',
            new_name='pic',
        ),
        migrations.AddField(
            model_name='videostream',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active stream within a channel'),
        ),
        migrations.AddField(
            model_name='videostreamset',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='video_stream_set_pic', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
