# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161126_0508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioStream',
        ),
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='videostream',
            name='stream_set',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
        migrations.DeleteModel(
            name='VideoStream',
        ),
        migrations.DeleteModel(
            name='VideoStreamSet',
        ),
    ]
