# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20161201_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='status')),
            ],
            options={
                'db_table': 'statuses',
            },
        ),
    ]
