# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20161210_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'professions',
                'verbose_name': '\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u044f',
                'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u0438',
            },
        ),
    ]
