# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-01 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videostreamset',
            options={'verbose_name': '\u0412\u0438\u0434\u0435\u043e \u043a\u0430\u043d\u0430\u043b', 'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e \u043a\u0430\u043d\u0430\u043b\u044b'},
        ),
        migrations.AlterField(
            model_name='videostream',
            name='active',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439 \u0441\u0442\u0440\u0438\u043c'),
        ),
        migrations.AlterField(
            model_name='videostreamset',
            name='pic',
            field=models.ImageField(default=1, upload_to='video_stream_set_pic', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
            preserve_default=False,
        ),
    ]
