# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_crm', '0002_auto_20161212_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'priorities',
                'verbose_name': '\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442',
                'verbose_name_plural': '\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442\u044b',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='time_creation',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 12, 19, 23, 7, 849104), verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
