# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_crm', '0003_auto_20161212_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract_crm.Project', verbose_name='\u041f\u0440\u043e\u0435\u043a\u0442')),
            ],
            options={
                'db_table': 'trackers',
                'verbose_name': '\u041e\u0442\u0434\u0435\u043b',
                'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abstract_crm.Task', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0430\u044f \u0437\u0430\u0434\u0430\u0447\u0430'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_creation',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 13, 7, 47, 18, 657501), verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='task',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abstract_crm.Tracker', verbose_name='\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 (\u043e\u0442\u0434\u0435\u043b)'),
        ),
    ]
