# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_crm', '0004_auto_20161213_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker',
            options={'verbose_name': '\u041e\u0442\u0434\u0435\u043b', 'verbose_name_plural': '\u041e\u0442\u0434\u0435\u043b\u044b'},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abstract_crm.Priority', verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abstract_crm.Project', verbose_name='\u041f\u0440\u043e\u0435\u043a\u0442'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abstract_crm.TaskStatus', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_creation',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 13, 9, 22, 17, 297787), verbose_name='\u0412\u0440\u0435\u043c\u044f \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
    ]
